name: Build Farasa ARM64

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build ARM64 Native Image
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/graalvm/graalvm-ce:21.3.0
          options: --platform linux/arm64 -v ${{ github.workspace }}:/app
          run: |
            gu install native-image
            cd /app

            native-image \
              --no-fallback \
              --static \
              --enable-http \
              --report-unsupported-elements-at-runtime \
              --target-arch=aarch64 \
              --target-os=linux \
              -cp "farasa_bin/FarasaDiacritizeJar.jar:farasa_bin/FarasaPOSJar.jar:farasa_bin/FarasaNERJar.jar:farasa_bin/ConstituencyParser.jar:farasa_bin/lib/FarasaSegmenterJar.jar:farasa_bin/lib/trove-3.0.3.jar:farasa_bin/lib/mallet.jar:farasa_bin/lib/mallet-deps.jar:farasa_bin/lib/weka.jar" \
              -H:Name=farasa_diacritizer_arm64 \
              com.qcri.farasa.diacritize.FarasaDiacritizer

      - name: Upload Output Binary
        uses: actions/upload-artifact@v4
        with:
          name: farasa_diacritizer_arm64
          path: farasa_diacritizer_arm64
